### PR TITLE
Kenneth/front end

### PR DESCRIPTION
**Pull request by kendevops**
#1 
I fetched from the data from the aws amplify created by @shu8 and then used it to populate my card data.

### CODE REVIEW

**Comment by shu8** [comment]
Login page:

image

**Comment by shu8** [comment]
@kendevops I think this can be merged after the search logic is finished, so I think we've decided on doing something like this:

```
filteredPeople = people.filter(fellow => Object.values(fellow).toString().includes(textToSearch)
```

for the search onsubmit

right?

**Comment by ivov** [comment]
We could zoom in on the specific values that we're interested in instead of `filteredPeople = people.filter(fellow => Object.values(fellow).toString().includes(textToSearch)` but for our purposes it's good!

**Comment by kendevops** [comment]
I have done the filter, though i implemented it to filter the pod names, so all the data fetched has to show then from there i filtered implemented a filter for the pods.

**Comment by shu8** [comment]
Will fill conflict now

**Comment by kendevops** [comment]
Alright, so we are hosting with heroku right?

**Comment by shu8** [comment]
Not sure why the GitHub interface was showing a conflict, I've merged this from the CLI instead. 🎉

**Comment by shu8** [comment]
@kendevops yeah! will deploy now

**Pull request merged**
